
stages:
  - test
  - deploy

test27:
  image: continuumio/miniconda:latest
  stage: test
  script:
    - echo "========== Setting up environment =========="
    - apt install -y python-dev > tmp.txt && echo 'apt deps installed'
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda config --add channels conda-forge  # ROOT channel
    - conda create -n test27 python=2.7 root=6 > tmp.txt && echo 'env created'
    - pip install root-numpy > tmp.txt && echo 'root-numpy installed'
    - source activate test27 > tmp.txt && echo 'activated'

#   HACK, psutil fails to build currently
    - echo "========== HACK install psutil (fails to build) =========="
    - conda install psutil > tmp.txt && echo 'psutil installed'

#   HACK, subprocess32 fails to build currently
    - echo "========== HACK install subprocess32 (fails to build) =========="
    - conda install subprocess32 > tmp.txt && echo 'subprocess32 installed'

    - echo "========== Install analysis =========="
    - pip install -e .

    - bash ci/test_runner.sh

    - bash ci/static_checker.sh

    - bash ci/testbuild_docs.sh

    - echo "========== All tests finished =========="

test36:
  image: continuumio/miniconda3:latest
  stage: test
  script:
    - echo "========== Setting up environment =========="
    - apt install -y python3-dev  > tmp.txt && echo 'apt deps installed'
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda config --add channels conda-forge  # ROOT channel
    - conda create -n test36 python=3.6 root=6 > tmp.txt && echo 'env created'
    - pip install root-numpy > tmp.txt && echo 'root-numpy installed'
    - source activate test36 > tmp.txt && echo 'activated'

#   HACK, psutil fails to build currently
    - echo "========== HACK install psutil (fails to build) =========="
    - conda install psutil > tmp.txt && echo 'psutil installed'

    - echo "========== Install analysis =========="
    - pip install -e .

    - bash ci/test_runner.sh

    - bash ci/static_checker.sh

    - bash ci/testbuild_docs.sh


    - echo "========== All tests finished =========="


test36_data_fail:
  image: continuumio/miniconda3:latest
  stage: test
  allow_failure: true
  script:
    - echo "========== Setting up environment =========="
    - apt install -y python3-dev  > tmp.txt && echo 'apt deps installed'
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda config --add channels conda-forge  # ROOT channel
    - conda create -n test36 python=3.6 root=6 > tmp.txt && echo 'env created'
    - pip install root-numpy > tmp.txt && echo 'root-numpy installed'
    - source activate test36 > tmp.txt && echo 'activated'

#   HACK, psutil fails to build currently
    - echo "========== HACK install psutil (fails to build) =========="
    - conda install psutil > tmp.txt && echo 'psutil installed'

    - echo "========== Install analysis =========="
    - pip install -e .

#   install test utilities
    - echo "========== Install test utilities =========="
    - conda install pytest coverage > tmp.txt && echo 'test utils installed'

#    run tests
    - echo "========== Running tests with coverage =========="
    - pytest tests/test_data.py  # fails for some unknown reason


build_apidoc:
  image: continuumio/miniconda3:latest
  stage: deploy
  only:
    - master
  script:
    - echo "========== Building docs =========="
    - echo "NotImplementedNotImplementedNotImplementedNotImplemented"
    - echo "========== Finished building and deploying docs =========="
