
stages:
  - test

test27:
  image: continuumio/anaconda
  stage: test
  script:
#   setup env
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    - conda info -a
    - conda config --add channels https://conda.anaconda.org/NLeSC  # ROOT channel
#    - conda config --add channels https://conda.anaconda.org/nlesc/label/dev
    - conda install python=2.7 root=6 root_numpy
#   install test utilities
    - conda install pytest coverage
#   install package
    - pip install git+https://github.com/ibab/root_pandas.git
    - pip install -e .
#     run tests
    - coverage run -m pytest .
    - coverage report --omit=/*/anaconda*/*


test36:
  image: continuumio/anaconda3
  stage: test
  script:
#   setup env
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    - conda info -a
    - conda config --add channels https://conda.anaconda.org/NLeSC  # ROOT channel
#    - conda config --add channels https://conda.anaconda.org/nlesc/label/dev
    - conda install python=3.6 root=6 root_numpy
#   install test utilities
    - conda install pytest coverage
#   install package
    - pip install git+https://github.com/ibab/root_pandas.git
    - pip install -e .
#    run tests
    - coverage run -m pytest .
    - coverage report --omit=/*/anaconda*/*

# Pylint does not yet work, throws error for a file in analysis/data
#
# Job: run PyLint
#
#run_pylint:
#    type: test
#    script:
#        - pip install pylint
#
#        - pip install -U pip
#        - pylint analysis/*/*.py

