
stages:
  - test
  - deploy

test27:
#  image: continuumio/anaconda
  image: continuumio/miniconda:latest
  stage: test
  script:
#   setup env
    - apt install -y python-dev
    - conda config --set always_yes yes --set changeps1 no
#    - conda update conda
    - conda info -a
    - conda config --add channels https://conda.anaconda.org/NLeSC  # ROOT channel
#    - conda config --add channels https://conda.anaconda.org/nlesc/label/dev
    - conda create -n test27 python=2.7 root=6 root-numpy libgcc gcc > tmp.txt && echo 'activated'
    - source activate test27 && echo 'activated'
#    - conda install python=2.7 root=6 root_numpy
#   install test utilities
    - conda install pytest coverage > tmp.txt && echo 'activated'
#   install package
#   HACK, psutil and subprocess32 fail to build currently
    - conda install psutil subprocess32 > tmp.txt && echo 'activated'
#    HACK, install manually deps
#    - conda install h5py PyYAML seaborn root_pandas > tmp.txt && echo 'activated'
#   HACK
#    - conda install -c serge-sans-paille gcc_49
#    - pip install git+https://github.com/ibab/root_pandas.git
    - pip install -e .
#     run tests
#    - coverage run -m pytest .
#    - coverage report --omit=/*/anaconda*/*


test36:
#  image: continuumio/anaconda3
  image: continuumio/miniconda3:latest
  stage: test
  script:
#   setup env
    - apt install -y python3-dev
    - conda config --set always_yes yes --set changeps1 no
#    - conda update conda
    - conda info -a
    - conda config --add channels https://conda.anaconda.org/NLeSC  # ROOT channel
#    - conda config --add channels https://conda.anaconda.org/nlesc/label/dev
    - conda create -n test36 python=3.6 root=6 root-numpy libgcc gcc > tmp.txt
    - source activate test36 > tmp.txt && echo 'activated'
#    - conda install python=3.6 root=6 root-numpy

#   install test utilities
    - conda install pytest coverage > tmp.txt && echo 'activated'
#   install package
#   HACK, psutil fails to build currently
    - conda install psutil > tmp.txt && echo 'activated'
#    - pip install git+https://github.com/ibab/root_pandas.git
# HACK: install deps manually...
#    - conda install psutil h5py PyYAML seaborn > tmp.txt && echo 'activated'
#   HACK
#    - conda install -c serge-sans-paille gcc_49

    - pip install -e .
#    run tests
#    - coverage run -m pytest .
#    - coverage report --omit=/*/anaconda*/*

#autodoc36:
#  image: continuumio/miniconda3:latest

# Pylint does not yet work, throws error for a file in analysis/data
#
# Job: run PyLint
#
#run_pylint:
#    type: test
#    script:
#        - pip install pylint
#
#        - pip install -U pip
#        - pylint analysis/*/*.py

